config/routes.rb
Rails.application.routes.draw do

  

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root :to => 'welcome#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end

   root 'welcome#index'
  

  resources :bestaccreditedstudentbranches
  
  get '/bestaccreditedstudentbranches/getname/:institution_membership_no' => 'bestaccreditedstudentbranches#getname'
  
  resources :bestcsiinternationalstudentseventhosts
  resources :highestsponsorshipofcsievents
  resources :longestcontinuoussbcs
  resources :facmaxpublishings

end

app/models/bestcsiinternationalstudentseventhost.rb
class Bestcsiinternationalstudentseventhost < ActiveRecord::Base
    belongs_to :users
end

app/controllers/bestcsiinternationalstudentseventhosts_controller.rb
class BestcsiinternationalstudentseventhostsController < ApplicationController
    
    before_action :set_award , only: [:edit,:update,:show,:destroy]
    before_action :authenticate_user!, except: [:index,:show]
    
    
    def index
        @bestcsiinternationalstudentseventhosts = Bestcsiinternationalstudentseventhost.all
    end
    
    def show
        
    end    
    
    def new
        @bestcsiinternationalstudentseventhost = Bestcsiinternationalstudentseventhost.new
    end
    
    def create
        @bestcsiinternationalstudentseventhost = Bestcsiinternationalstudentseventhost.new(bestcsiinternationalstudentseventhost_params)
        
        if @bestcsiinternationalstudentseventhost.save
            redirect_to @bestcsiinternationalstudentseventhost
        else
            render "new"
        end    
    end
    
    def edit
        
        
    end
    
    def update
        if @bestcsiinternationalstudentseventhost.update(bestcsiinternationalstudentseventhost_params)
            redirect_to @bestcsiinternationalstudentseventhost
        else
            render "edit"
        end    
    end
    
    def destroy
        @bestcsiinternationalstudentseventhost.destroy
        redirect_to bestcsiinternationalstudentseventhostes_path
    end
    
    private
    
    def bestcsiinternationalstudentseventhost_params
       params.require(:bestcsiinternationalstudentseventhost)
       .permit(:institution_membership_no,:validity,:name_of_the_institution,:postal_address,:city,:pin,:state,:phone_number,:emailID,
       :SBC_name,:SBC_designation,:SBC_department,:SBC_emailID,:SBC_phone_number,:Institution_membership_joining_date,
       :Institution_membership_valid_till,:no_of_csi_voulenteers,:no_of_csi_voulenteers_added)
    end
    
    def set_award
       @bestcsiinternationalstudentseventhost = bestcsiinternationalstudentseventhost.find(params[:id]) 
    end
end

app/helpers/bestcsiinternationalstudentseventhosts_helper.rb
module BestcsiinternationalstudentseventhostsHelper
end

app/views/bestcsiinternationalstudentseventhosts/_form.html.erb
<%= form_for @bestcsiinternationalstudentseventhost, :html => {:class => "form-horizontal"} do |f| %>
    <div class="form-group">
      <%= f.label :institution_membership_no %>
      <%= f.text_field :institution_membership_no , class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :validity %>
      <%= f.text_field :validity, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :name_of_the_institution %>
      <%= f.text_field :name_of_the_institution, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :postal_address %>
      <%= f.text_field :postal_address, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :city %>
      <%= f.text_field :city, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :pin %>
      <%= f.text_field :pin , class: "form-control"%>
    </div>
    <div class="form-group">
      <%= f.label :state %>
      <%= f.text_field :state , class: "form-control"%>
    </div>
    <div class="form-group">
      <%= f.label :phone_number %>
      <%= f.text_field :phone_number , class: "form-control"%>
    </div>
    <div class="form-group">
      <%= f.label :emailID %>
      <%= f.email_field :emailID, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :SBC_name %>
      <%= f.text_field :SBC_name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :SBC_designation %>
      <%= f.text_field :SBC_designation , class: "form-control"%>
    </div>
    <div class="form-group">
      <%= f.label :SBC_department %>
      <%= f.text_field :SBC_department, class: "form-control" %>
    </div>
    
    <div class="form-group">
      <%= f.label :SBC_emailID %>
      <%= f.text_field :SBC_emailID , class: "form-control"%>
    </div>
    <div class="form-group">
      <%= f.label :SBC_phone_number %>
      <%= f.text_field :SBC_phone_number , class: "form-control"%>
    </div>
    <div class="form-group">
      <%= f.label :Institution_membership_joining_date %>
      <%= f.text_field :Institution_membership_joining_date, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :Institution_membership_valid_till %>
      <%= f.text_field :Institution_membership_valid_till , class: "form-control"%>
    </div>
    <div class="form-group">
      <%= f.label :no_of_csi_voulenteers %>
      <%= f.text_field :no_of_csi_voulenteers, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :no_of_csi_voulenteers_added %>
      <%= f.text_field :no_of_csi_voulenteers_added, class: "form-control" %>
    </div>
    
    
    
    <div class="form-group">
        <div class="col-md-offset-5 col-md-2">
            <%= f.submit "Submit" , class: "btn btn-primary" %>
        </div>
    </div>
<% end %>   

app/views/bestcsiinternationalstudentseventhosts/edit.html.erb
<h2>Edit award details</h2>

<%= render "form" %>

app/views/bestcsiinternationalstudentseventhosts/index.html.erb
<h2>bestcsiinternationalstudentseventhosts</h2>

<% @bestcsiinternationalstudentseventhosts.each do |i| %>
    <%= link_to i.name_of_the_institution , i  %>
<% end %>    

app/views/bestcsiinternationalstudentseventhosts/new.html.erb
<h2 align="center">Enter award details for Best CSI International Students Event</h2>

<%= render "form" %>

app/views/bestcsiinternationalstudentseventhosts/show.html.erb
<h2>Submitted Details</h2>

    <div>
      <%= @bestcsiinternationalstudentseventhost.institution_membership_no %>
      
    </div>
    <div>
      <%= @bestcsiinternationalstudentseventhost.validity %>
      
    </div>
    <div>
      <%=  @bestcsiinternationalstudentseventhost.name_of_the_institution %>
    
    </div>
    <div>
      <%=  @bestcsiinternationalstudentseventhost.postal_address %>
  
    </div>
    <div>
      <%=  @bestcsiinternationalstudentseventhost.city %>
   
    </div>
    <div>
      <%=  @bestcsiinternationalstudentseventhost.pin %>
  
    </div>
    <div>
      <%=  @bestcsiinternationalstudentseventhost.state %>
    
    </div>
    <div>
      <%=  @bestcsiinternationalstudentseventhost.phone_number %>
  
    </div>
    <div>
      <%=  @bestcsiinternationalstudentseventhost.emailID %>
 
    </div>
    <div>
      <%=  @bestcsiinternationalstudentseventhost.SBC_name %>
      
    </div>
    <div>
      <%=  @bestcsiinternationalstudentseventhost.SBC_designation %>
   
    </div>
    <div>
      <%=  @bestcsiinternationalstudentseventhost.SBC_department %>
      
    </div>
    
    <div>
      <%=  @bestcsiinternationalstudentseventhost.SBC_emailID %>
     
    </div>
    <div>
      <%=  @bestcsiinternationalstudentseventhost.SBC_phone_number %>
      
    </div>
    <div>
      <%=  @bestcsiinternationalstudentseventhost.Institution_membership_joining_date %>
      
    </div>
    <div>
      <%=  @bestcsiinternationalstudentseventhost.Institution_membership_valid_till %>
      
    </div>
    <div>
      <%=  @bestcsiinternationalstudentseventhost.no_of_csi_voulenteers %>
      
    </div>
    <div>
      <%=  @bestcsiinternationalstudentseventhost.no_of_csi_voulenteers_added %>
      
    </div>

<%= link_to "Edit Details" ,   edit_bestaccreditedstudentbranch_path(@bestcsiinternationalstudentseventhost) %> |    
<%= link_to "Delete" , bestcsiinternationalstudentseventhost_path(@bestcsiinternationalstudentseventhost), method: :delete , data: {confirm: "Are you sure ?"}  %> |  
<%= link_to "Apply for another Award" , root_path %>