config/routes.rb
Rails.application.routes.draw do

  

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root :to => 'welcome#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end

   root 'welcome#index'
  

  resources :bestaccreditedstudentbranches
  
  get '/bestaccreditedstudentbranches/getname/:institution_membership_no' => 'bestaccreditedstudentbranches#getname'
  
  resources :bestcsiinternationalstudentseventhosts
  resources :highestsponsorshipofcsievents
  resources :longestcontinuoussbcs
  resources :facmaxpublishings

end

app/models/bestaccreditedstudentbranch.rb
class Bestaccreditedstudentbranch < ActiveRecord::Base
    belongs_to :users
    
    
end

app/controllers/bestaccreditedstudentbranches_controller.rb
class BestaccreditedstudentbranchesController < ApplicationController
    
    before_action :set_award , only: [:edit,:update,:show,:destroy]
    before_action :authenticate_user!, except: [:show]
    
    def getname
        @bestaccreditedstudentbranch = Bestaccreditedstudentbranch.where(institution_membership_no: params[:institution_membership_no]).first
    end
    
    def index
        @bestaccreditedstudentbranches = Bestaccreditedstudentbranch.all
    end
    
    def show
        
    end    
    
    def new
        @bestaccreditedstudentbranch = Bestaccreditedstudentbranch.new
    end
    
    def create
        @bestaccreditedstudentbranch = Bestaccreditedstudentbranch.new(bestaccreditedstudentbranch_params)
        
        if @bestaccreditedstudentbranch.save
            flash[:notice] = " Your response has been recorded"
            redirect_to @bestaccreditedstudentbranch
        else
            render "new"
        end    
    end
    
    def edit
        
        
    end
    
    def update
        if @bestaccreditedstudentbranch.update(bestaccreditedstudentbranch_params)
            flash[:notice] = "Your response has been modified"
            redirect_to @bestaccreditedstudentbranch
        else
            render "edit"
        end    
    end
    
    def destroy
        @bestaccreditedstudentbranch.destroy
        flash[:notice] = "Your response has been deleted"
        redirect_to root_path
    end
    
    private
    
    def bestaccreditedstudentbranch_params
       params.require(:bestaccreditedstudentbranch)
       .permit(:institution_membership_no,:name_of_the_institution,:postal_address,:city,:pin,:state,:phone_number,:emailID,
       :SBC_name,:SBC_designation,:SBC_department,:SBC_emailID,:SBC_phone_number,:SBC_CSI_membership_no,
       :no_of_csi_voulenteers,:no_of_csi_voulenteers_added)
    end
    
    def set_award
       @bestaccreditedstudentbranch = Bestaccreditedstudentbranch.find(params[:id]) 
    end 
end

app/helpers/bestaccreditedstudentbranches_helper.rb
module BestaccreditedstudentbranchesHelper
end

app/views/bestaccreditedstudentbranches/_form.html.erb
<%= form_for @bestaccreditedstudentbranch , :html => {:class => "form-horizontal"} do |f| %>
    <div class="form-group">
      <%= f.label :institution_membership_no , "Institution Membership No:"%>
      <%= f.text_field :institution_membership_no , class: "form-control" , id:"institution_membership_no_id" %>
    </div>
    <div class="form-group">
      <%= f.label :name_of_the_institution %>
      <%= f.text_field :name_of_the_institution , class: "form-control" , id:"name_of_the_institution_id"%>
    </div>
     <div class="row">
    <div class="form-group col-md-4">
      <%= f.label :postal_address %>
      <%= f.text_field :postal_address , class: "form-control" , id:"postal_address_id"%>
    </div>
   
      
    
    <div class="form-group col-md-4">
      <%= f.label :city %>
      <%= f.text_field :city, class: "form-control" , id:"city_id"%>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :pin %>
      <%= f.text_field :pin, class: "form-control", id:"pin_id" %>
    </div>
    </div>
    <div class="row">
    <div class="form-group col-md-4">
      <%= f.label :state %>
      <%= f.text_field :state , class: "form-control", id:"state_id"%>
    </div>

    
    
      
    
    <div class="form-group col-md-4">
      <%= f.label :phone_number %>
      <%= f.text_field :phone_number, class: "form-control", id:"phone_number_id" %>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :emailID %>
      <%= f.email_field :emailID, class: "form-control", id:"emailID_id" %>
    </div>
    </div>
    <div class="form-group">
      <%= f.label :SBC_name , "SBC Name" %>
      <%= f.text_field :SBC_name, class: "form-control" , id:"SBC_name_id"%>
    </div>
    <div class="row">
      
    
    <div class="form-group col-md-3">
      <%= f.label :SBC_designation , "SBC Designation" %>
      <%= f.text_field :SBC_designation , class: "form-control" , id:"SBC_designation_id"%>
    </div>
    <div class="form-group col-md-3">
      <%= f.label :SBC_department , "SBC Department" %>
      <%= f.text_field :SBC_department, class: "form-control" , id:"SBC_department_id"%>
    </div>
    
      
    
    <div class="form-group col-md-3">
      <%= f.label :SBC_emailID , "SBC Email ID" %>
      <%= f.text_field :SBC_emailID , class: "form-control" , id:"SBC_emailID_id"%>
    </div>
    <div class="form-group col-md-3">
      <%= f.label :SBC_phone_number , "SBC Phone number" %>
      <%= f.text_field :SBC_phone_number , class: "form-control" , id:"SBC_phone_number_id"%>
    </div>
    </div>
    
    <div class="row">
      
    
    <div class="form-group col-md-4">
      <%= f.label :SBC_CSI_membership_no , "SBC CSI Membership No" %>
      <%= f.text_field :SBC_CSI_membership_no , class: "form-control", id:"SBC_CSI_membership_no_id" %>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :no_of_csi_voulenteers %>
      <%= f.text_field :no_of_csi_voulenteers , class: "form-control", id:"no_of_csi_voulenteers_id"%>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :no_of_csi_voulenteers_added %>
      <%= f.text_field :no_of_csi_voulenteers_added , class: "form-control" , id:"no_of_csi_voulenteers_added_id"%>
    </div>
    </div>
    
    
    <div class="form-group">
        <div class="col-md-offset-5 col-md-2">
            <%= f.submit "Submit" , class: "btn btn-primary btn-lg" %>
        </div>
    </div>
<% end %>   
  

     

app/views/bestaccreditedstudentbranches/getname.js.erb
$('#name_of_the_institution_id').val('<%= @bestaccreditedstudentbranch.name_of_the_institution %>');
$('#postal_address_id').val('<%= @bestaccreditedstudentbranch.postal_address %>');
$('#city_id').val('<%= @bestaccreditedstudentbranch.city %>');
$('#pin_id').val('<%= @bestaccreditedstudentbranch.pin %>');
$('#state_id').val('<%= @bestaccreditedstudentbranch.state %>');
$('#phone_number_id').val('<%= @bestaccreditedstudentbranch.phone_number %>');
$('#emailID_id').val('<%= @bestaccreditedstudentbranch.emailID %>');
$('#SBC_name_id').val('<%= @bestaccreditedstudentbranch.SBC_name %>');
$('#SBC_designation_id').val('<%= @bestaccreditedstudentbranch.SBC_designation %>');
$('#SBC_department_id').val('<%= @bestaccreditedstudentbranch.SBC_department %>');
$('#SBC_emailID_id').val('<%= @bestaccreditedstudentbranch.SBC_emailID %>');
$('#SBC_phone_number_id').val('<%= @bestaccreditedstudentbranch.SBC_phone_number %>');
$('#SBC_CSI_membership_no_id').val('<%= @bestaccreditedstudentbranch.SBC_CSI_membership_no %>');
$('#no_of_csi_voulenteers_id').val('<%= @bestaccreditedstudentbranch.no_of_csi_voulenteers %>');
$('#no_of_csi_voulenteers_added_id').val('<%= @bestaccreditedstudentbranch.no_of_csi_voulenteers_added %>');

app/views/bestaccreditedstudentbranches/index.html.erb
<h2>BEST ACCREDITED STUDENT BRANCHES</h2>
<% j=1 %>
<% @bestaccreditedstudentbranches.each do |i| %>
    
    <%= j %> ) <%= link_to i.name_of_the_institution , i  %>
    <% j+=1 %>
    <br>
<% end %>    

app/views/bestaccreditedstudentbranches/new.html.erb
<h2 align="center">Enter Award Details For Best Accredited Student Branch</h2>

<%= render "form" %>

app/views/bestaccreditedstudentbranches/show.html.erb
<h2 align="center">Submitted Details</h2>

    <div class="submitted-details">
      <p>Institution Membership No: <%= @bestaccreditedstudentbranch.institution_membership_no %></p>
      
    
      <p>Institution Name: <%=  @bestaccreditedstudentbranch.name_of_the_institution %></p>
    
    
      <p>Address:  <%=  @bestaccreditedstudentbranch.postal_address %></p>
  
   
      <p>City:  <%=  @bestaccreditedstudentbranch.city %></p>
   
    
      <p>Pin:  <%=  @bestaccreditedstudentbranch.pin %></p>
  
   
      <p>State:  <%=  @bestaccreditedstudentbranch.state %></p>
    
    
      <p>Phone Number:  <%=  @bestaccreditedstudentbranch.phone_number %></p>
  
    
      <p>Email:  <%=  @bestaccreditedstudentbranch.emailID %></p>
 
    
      <p>SBC Name:  <%=  @bestaccreditedstudentbranch.SBC_name %></p>
      
    
      <p>SBC Designation:  <%=  @bestaccreditedstudentbranch.SBC_designation %></p>
   
    
      <p>SBC DEpartment:  <%=  @bestaccreditedstudentbranch.SBC_department %></p>
      
   
      <p>SBC email:  <%=  @bestaccreditedstudentbranch.SBC_emailID %></p>
     
    
      <p>SBC contact Number:  <%=  @bestaccreditedstudentbranch.SBC_phone_number %></p>
      
    
      <p>SBC CSI Membership No:  <%=  @bestaccreditedstudentbranch.SBC_CSI_membership_no %></p>
      
 
      <p>No of CSI voulenteers:  <%=  @bestaccreditedstudentbranch.no_of_csi_voulenteers %></p>
      
   
      <p>No of CSI voulenteers added:  <%=  @bestaccreditedstudentbranch.no_of_csi_voulenteers_added %></p>
      
    </div>


<div class="showpage-links">
  <%= link_to "Edit Details" ,   edit_bestaccreditedstudentbranch_path(@bestaccreditedstudentbranch) %> |
  <%= link_to "Delete" , bestaccreditedstudentbranch_path(@bestaccreditedstudentbranch), method: :delete , data: {confirm: "Are you sure ?"}  %> | 
  <%= link_to "Apply for another Award" , root_path %>
</div>    