config/routes.rb
Rails.application.routes.draw do

  

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root :to => 'welcome#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end

   root 'welcome#index'
  

  resources :bestaccreditedstudentbranches
  
  get '/bestaccreditedstudentbranches/getname/:institution_membership_no' => 'bestaccreditedstudentbranches#getname'
  
  resources :bestcsiinternationalstudentseventhosts
  resources :highestsponsorshipofcsievents
  resources :longestcontinuoussbcs
  resources :facmaxpublishings

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<h1 align="center" id="award-banner">AWARDS</h1>

<div class="container award-area">
    
<div class="award-title">
    <h2><%= link_to "Best Accredited Student Branch Award" , new_bestaccreditedstudentbranch_path %> 
    <% if current_user.try(:admin?) %> |
    <%= link_to "All Awards Details Submitted" , bestaccreditedstudentbranches_path %>
    <% end %>
    </h2>
</div>

<div class="award-title">
    <h2><%= link_to "Best CSI International students event host Award" , new_bestcsiinternationalstudentseventhost_path %>
    <% if current_user.try(:admin?) %> |
    <%= link_to "All Awards Details Submitted" , bestcsiinternationalstudentseventhosts_path %>
    <% end %>
    </h2>
</div>

<div class="award-title">
   <h2><%= link_to "Highest sponsorship of CSI events Award" , new_highestsponsorshipofcsievent_path %> 
    <% if current_user.try(:admin?) %> |
    <%= link_to "All Awards Details Submitted" , highestsponsorshipofcsievents_path %>
    <% end %>
    </h2> 
</div>

<div class="award-title">
    <h2><%= link_to "Longest continuous SBC Award" , new_longestcontinuoussbc_path %> 
    <% if current_user.try(:admin?) %> |
    <%= link_to "All Awards Details Submitted" , longestcontinuoussbcs_path %>
    <% end %>
    </h2>
</div>

<div class="award-title">
   <h2><%= link_to "Faculty with maximum publishing in CSI Publications Award" , new_facmaxpublishing_path %> 
    <% if current_user.try(:admin?) %> |
    <%= link_to "All Awards Details Submitted" , facmaxpublishings_path %>
    <% end %>
    </h2> 
</div>

</div>