config/routes.rb
Rails.application.routes.draw do

  

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root :to => 'welcome#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end

   root 'welcome#index'
  

  resources :bestaccreditedstudentbranches
  
  get '/bestaccreditedstudentbranches/getname/:institution_membership_no' => 'bestaccreditedstudentbranches#getname'
  
  resources :bestcsiinternationalstudentseventhosts
  resources :highestsponsorshipofcsievents
  resources :longestcontinuoussbcs
  resources :facmaxpublishings

end

app/models/highestsponsorshipofcsievent.rb
class Highestsponsorshipofcsievent < ActiveRecord::Base
    belongs_to :users
end

app/controllers/highestsponsorshipofcsievents_controller.rb
class HighestsponsorshipofcsieventsController < ApplicationController
    before_action :set_award , only: [:edit,:update,:show,:destroy]
    before_action :authenticate_user!, except: [:index,:show]
    
    
    def index
        @highestsponsorshipofcsievents = Highestsponsorshipofcsievent.all
    end
    
    def show
        
    end    
    
    def new
        @highestsponsorshipofcsievent = Highestsponsorshipofcsievent.new
    end
    
    def create
        @highestsponsorshipofcsievent = Highestsponsorshipofcsievent.new(highestsponsorshipofcsievent_params)
        
        if @highestsponsorshipofcsievent.save
            redirect_to @highestsponsorshipofcsievent
        else
            render "new"
        end    
    end
    
    def edit
        
        
    end
    
    def update
        if @highestsponsorshipofcsievent.update(highestsponsorshipofcsievent_params)
            redirect_to @highestsponsorshipofcsievent
        else
            render "edit"
        end    
    end
    
    def destroy
        @highestsponsorshipofcsievent.destroy
        redirect_to highestsponsorshipofcsieventes_path
    end
    
    private
    
    def highestsponsorshipofcsievent_params
       params.require(:highestsponsorshipofcsievent)
       .permit(:institution_membership_no,:validity,:name_of_the_institution,:postal_address,:city,:pin,:state,:phone_number,:emailID,
       :SBC_name,:SBC_designation,:SBC_department,:SBC_emailID,:SBC_phone_number,:Institution_membership_joining_date,
       :Institution_membership_valid_till,:no_of_csi_voulenteers,:no_of_csi_voulenteers_added)
    end
    
    def set_award
       @highestsponsorshipofcsievent = highestsponsorshipofcsievent.find(params[:id]) 
    end
end

app/helpers/highestsponsorshipofcsievents_helper.rb
module HighestsponsorshipofcsieventsHelper
end

app/views/highestsponsorshipofcsievents/_form.html.erb
<%= form_for @highestsponsorshipofcsievent, :html => {:class => "form-horizontal"} do |f| %>
    <div class="form-group">
      <%= f.label :institution_membership_no %>
      <%= f.text_field :institution_membership_no , class: "form-control"%>
    </div>
    <div class="form-group">
      <%= f.label :validity %>
      <%= f.text_field :validity , class: "form-control"%>
    </div>
    <div class="form-group">
      <%= f.label :name_of_the_institution %>
      <%= f.text_field :name_of_the_institution, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :postal_address %>
      <%= f.text_field :postal_address, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :city %>
      <%= f.text_field :city, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :pin %>
      <%= f.text_field :pin, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :state %>
      <%= f.text_field :state , class: "form-control"%>
    </div>
    <div class="form-group">
      <%= f.label :phone_number %>
      <%= f.text_field :phone_number, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :emailID %>
      <%= f.email_field :emailID, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :SBC_name %>
      <%= f.text_field :SBC_name , class: "form-control"%>
    </div>
    <div class="form-group">
      <%= f.label :SBC_designation %>
      <%= f.text_field :SBC_designation , class: "form-control"%>
    </div>
    <div class="form-group">
      <%= f.label :SBC_department %>
      <%= f.text_field :SBC_department, class: "form-control" %>
    </div>
    
    <div class="form-group">
      <%= f.label :SBC_emailID %>
      <%= f.text_field :SBC_emailID, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :SBC_phone_number %>
      <%= f.text_field :SBC_phone_number , class: "form-control"%>
    </div>
    <div class="form-group">
      <%= f.label :Institution_membership_joining_date %>
      <%= f.text_field :Institution_membership_joining_date, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :Institution_membership_valid_till %>
      <%= f.text_field :Institution_membership_valid_till, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :no_of_csi_voulenteers %>
      <%= f.text_field :no_of_csi_voulenteers, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :no_of_csi_voulenteers_added %>
      <%= f.text_field :no_of_csi_voulenteers_added , class: "form-control"%>
    </div>
    
    
    
    <div class="form-group">
        <div class="col-md-offset-5 col-md-2">
            <%= f.submit "Submit" , class: "btn btn-primary" %>
        </div>
    </div>
<% end %>   

app/views/highestsponsorshipofcsievents/edit.html.erb
<h2>Edit award details</h2>

<%= render "form" %>

app/views/highestsponsorshipofcsievents/index.html.erb
<h2>Highestsponsorshipofcsievents</h2>

<% @highestsponsorshipofcsievents.each do |i| %>
    <%= link_to i.name_of_the_institution , i  %>
<% end %>    

app/views/highestsponsorshipofcsievents/new.html.erb
<h2 align="center">Enter award details for Highest Sponsorship of Events</h2>

<%= render "form" %>

app/views/highestsponsorshipofcsievents/show.html.erb
<h2>Submitted Details</h2>

    <div>
      <%= @highestsponsorshipofcsievent.institution_membership_no %>
      
    </div>
    <div>
      <%= @bestcsiinternationalstudentseventhost.validity %>
      
    </div>
    <div>
      <%=  @highestsponsorshipofcsievent.name_of_the_institution %>
    
    </div>
    <div>
      <%=  @highestsponsorshipofcsievent.postal_address %>
  
    </div>
    <div>
      <%=  @highestsponsorshipofcsievent.city %>
   
    </div>
    <div>
      <%=  @highestsponsorshipofcsievent.pin %>
  
    </div>
    <div>
      <%=  @highestsponsorshipofcsievent.state %>
    
    </div>
    <div>
      <%=  @highestsponsorshipofcsievent.phone_number %>
  
    </div>
    <div>
      <%=  @highestsponsorshipofcsievent.emailID %>
 
    </div>
    <div>
      <%=  @highestsponsorshipofcsievent.SBC_name %>
      
    </div>
    <div>
      <%=  @highestsponsorshipofcsievent.SBC_designation %>
   
    </div>
    <div>
      <%=  @highestsponsorshipofcsievent.SBC_department %>
      
    </div>
    
    <div>
      <%=  @highestsponsorshipofcsievent.SBC_emailID %>
     
    </div>
    <div>
      <%=  @highestsponsorshipofcsievent.SBC_phone_number %>
      
    </div>
    <div>
      <%=  @bestcsiinternationalstudentseventhost.Institution_membership_joining_date %>
      
    </div>
    <div>
      <%=  @bestcsiinternationalstudentseventhost.Institution_membership_valid_till %>
      
    </div>
    <div>
      <%=  @highestsponsorshipofcsievent.no_of_csi_voulenteers %>
      
    </div>
    <div>
      <%=  @highestsponsorshipofcsievent.no_of_csi_voulenteers_added %>
      
    </div>

<%= link_to "Edit Details" ,   edit_bestaccreditedstudentbranch_path(@highestsponsorshipofcsievent) %> |      
<%= link_to "Delete" , highestsponsorshipofcsievent_path(@highestsponsorshipofcsievent), method: :delete , data: {confirm: "Are you sure ?"}  %> |  
<%= link_to "Apply for another Award" , root_path %>